### ISSUE TITLE
Container not reflecting changes in local source files unless container is re-installed

### ISSUE THREAD

**Issue by MaxZwarenstein** [wordup-dev/wordup-cli#16]
When I save template and theme files in VS code; and afterwards refresh the web browser for the docker container of the site, changes are not reflected in the web browser tab of the site. 

This makes debugging incredibly slow. How do I quickly reflect changes to the source code in my containerized WordPress installation?

**Comment by shry** [comment]
When you setup your project folder structure according to the wordup documentation (https://docs.wordup.dev/development), your source code folder is mounted to the wordup docker container. That means all changes in your theme source code should be visible directly in the browser/WordPress installation. Perhaps you have changed the folder structure after running the wordup service with `wordup install`?
