### ISSUE TITLE
[Bug] wordup export error

### ISSUE THREAD

**Issue by jackjwilliams** [wordup-dev/wordup-cli#2]
Everytime I run the wordup export command, it throws the following error (even though the server is running):

`Your project is not running, please use wordup install or wordup start`

Additionally, I'm kind of new to wordpress development (but I've been doing react dev for a few years). The folder structure is a little confusing - after development I just need to be able to upload a zip file to my WordPress site for my plugin. I'm guessing that is what the 'wordup export' command is for?

**Comment by shry** [comment]
Thanks for you bug report. Could you provide me some additional informations: 
* System: Mac & windows ?
* When you run `wordup list` , are you getting some results ?

Your question: 
> I'm guessing that is what the 'wordup export' command is for?

Yes, You can upload the exported zip file (under ./dist) directly to another WordPress website (Under WordPress - Admin: Plugins -> Add new -> Upload plugin)

**Comment by jackjwilliams** [comment]
System: Windows

Wordup list output:

```
C:\Projects\Personal\techlyplugins\techly [master +7 ~0 -0 !]> wordup list
NAME                INSTALLED LISTENING             PATH                                      ID
Techly              ✔         http://localhost:8000 C:\Projects\Personal\techlyplugins\techly 47a3bdc7ad4ba44eddaaa34e32cf1e7fcd5ad2b7
```

Docker ps
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                  NAMES
2861c7257911        wordup-wp:1.0       "docker-entrypoint.s…"   17 hours ago        Up 2 hours          0.0.0.0:8000->80/tcp   techly_wordpress_1
d565b03803cc        mariadb:latest      "docker-entrypoint.s…"   17 hours ago        Up 2 hours          3306/tcp               techly_db_1
```

**Comment by shry** [comment]
It seems that a docker command is not escaped correctly on windows. I will fix this asap. Thanks for your contribution

**Comment by jackjwilliams** [comment]
No problem, thank you for this streamlined dev setup!

I just wanted to focus on plugin development, not all the setup needed to just get going. This did exactly that.

Let me know when you drop a new version

**Comment by shry** [comment]
I have released a new version v.0.2.3 
This bug should be fixed with this version, i have tested it on a windows machine, however if you still have problems let me know.

**Comment by jackjwilliams** [comment]
That fixed it, ty sir!
