### ISSUE TITLE
Cant install with WSL2

### ISSUE THREAD

**Issue by GrotenM** [wordup-dev/wordup-cli#32]
Hello,

currently I'm using Ubuntu 18.04 on WSL2. When I try to install (wordup install) a project I get the following error:

❯ wordup install
Installing wordup project and connected docker containers (can take some minutes)... -
 ›   Error: There was an error while booting the docker containers. Perhaps the port is already taken.

Other docker containers are running without problems.

**Comment by shry** [comment]
This was a bug in the docker container, see #29 
Please update to the new version 0.7.4
