### ISSUE TITLE
Delete completely a project

### ISSUE THREAD

**Issue by globdug** [wordup-dev/wordup-cli#37]
Hello,
I have created two project just to try. Then I deleted theme with `wordup stop -d --delete` and deleted the folders of these project.
Then I created another project and when I type `wordup start` I receive this error :

> --- Currently running wordup projects: project1,project2 ---
> 
> Installing wordup project and connected docker containers (can take some minutes)... -
>  »   Error: There was an error while booting the docker containers. Perhaps the port is already       
>  »   taken.

How can I delete those projects?

**Comment by shry** [comment]
It depends on the version you are running. 

The new v1.0.0 has a --force flag for the `wordup stop` command. But it only works for new projects created with this version and its **not** backwards compatible with old projects.

But you have always the option to delete the docker containers manually. Run: `docker ps --filter label=wordup.dev` and delete the corresponding containers with `docker rm -f <container-id>`

**Comment by globdug** [comment]
Thank you very much, I deleted them manually. :)
