### ISSUE TITLE
wordup install error: ssmtp has no installation candidate

### ISSUE THREAD

**Issue by nicostuhlfauth** [wordup-dev/wordup-cli#7]
I just installed wordup on my computer and created a new project using `wordup init`. Since the install did not complete automatically, I decided to run `wordup install` manually. Same problem again, so here is my error log:

> Installing wordup project and connected docker containers (can take some minutes)
> Building wordpress
> Step 1/10 : FROM wordpress:latest
>  ---> 4ba1e63bd20c
> Step 2/10 : ARG USER_ID
>  ---> Using cache
>  ---> fe806a2cc2e1
> Step 3/10 : ARG GROUP_ID
>  ---> Using cache
>  ---> 4897ae2226d0
> Step 4/10 : COPY php.conf.ini /usr/local/etc/php/conf.d/conf.ini
>  ---> Using cache
>  ---> e46ec8002a36
> Step 5/10 : RUN apt-get update &&       apt-get install -y ssmtp
>  ---> Running in 9e62452221d5
> Get:1 http://security-cdn.debian.org/debian-security buster/updates InRelease [39.1 kB]
> Get:2 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [22.8 kB]
> Get:3 http://cdn-fastly.deb.debian.org/debian buster InRelease [118 kB]
> Get:4 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [46.8 kB]
> Get:5 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7897 kB]
> Fetched 8124 kB in 3s (3149 kB/s)
> Reading package lists...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Package ssmtp is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'ssmtp' has no installation candidate
> Service 'wordpress' failed to build: The command '/bin/sh -c apt-get update &&  apt-get install -y ssmtp' returned a non-zero code: 100
>  »   Error: There was an error while booting the docker containers. Perhaps the port is already taken.

My installed wordup version: `wordup-cli/0.6.2 win32-x64 node-v11.10.0`

My docker info:

> Containers: 3
>  Running: 0
>  Paused: 0
>  Stopped: 3
> Images: 6
> Server Version: 18.09.2
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
> runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
> init version: fec3683
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 4.9.125-linuxkit
> Operating System: Docker for Windows
> OSType: linux
> Architecture: x86_64
> CPUs: 2
> Total Memory: 1.934GiB
> Name: linuxkit-00155d1b4101
> ID: AKZ7:EGAJ:V5R4:4AJN:RNF2:DZSI:SJ25:R27E:DQ3P:MXNI:KW6C:FXI7
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): true
>  File Descriptors: 22
>  Goroutines: 47
>  System Time: 2019-07-15T14:01:34.9077291Z
>  EventsListeners: 1
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> Product License: Community Engine
>

**Comment by shry** [comment]
Thank you for your submit. This bug will be solved in the next release, because we will change the docker build process. We will integrate packaged containers from the docker hub, which should prevent this kind of bugs.

**Comment by nicostuhlfauth** [comment]
Ok thanks for your response @shry. Is there any workaround until the next version will be released?

**Comment by shry** [comment]
I will commit today some changes to the master branch. You could `git clone` the master branch and overwrite the wordup-cli folder on the system. 
After some testing, i will probably release the version tomorrow on npm.

**Comment by shry** [comment]
I have just released a new version v0.7.0 with a bugfix. Thank you for your contribution

**Comment by nicostuhlfauth** [comment]
Thanks for your bugfix. However, with v0.7.0 I'm running into a new issue:

> ERROR: for agr-website_mail_1  Cannot start service mail: driver failed programming external connectivity on endpoint agr-website_mail_1 (3369efd6c47ab5b2c8a16139ff2aabd955e65e23d35e5a82281c87704833cbc7): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8001:tcp:172.20.0.2:8025: input/output error

**Comment by shry** [comment]
Have you checked if old containers are running with `docker ps` ? What could help also, is to restart docker. It seems to be that there is sometimes an issue with docker for win: https://github.com/docker/for-win/issues/573

**Comment by nicostuhlfauth** [comment]
I removed all containers and restarted docker. Now there's a problem with the DB connection. Seems like the maria db container does not start 😢

**Comment by shry** [comment]
Thats very strange. Do you have the newest version of Docker Desktop for Windows installed?

**Comment by nicostuhlfauth** [comment]
Yes, `version 18.09.2, build 6247962` is installed.

**Comment by shry** [comment]
Ok. Could you provide the log files? The mariadb container has no open port, that's why it should be the least problamatic . What happens if you just run the maridb container alone: `docker run -e MYSQL_ROOT_PASSWORD=my-secret-pw mariadb:latest` ?

**Comment by shry** [comment]
I think i have solved this issue. The mariadb container tends to be very slow on Windows. At least on my system. I switched to version 10.3 and now its ok :)
